export const Users = [
    {
      id: 1,
      profilePicture: "assets/person/1.png",
      username: "Sarath Fonseka",
    },
    {
      id: 2,
      profilePicture: "assets/person/2.jpeg",
      username: "John Doe",
    },
    {
      id: 3,
      profilePicture: "assets/person/3.jpeg",
      username: "Jane Smith",
    },
    {
      id: 4,
      profilePicture: "assets/person/4.jpeg",
      username: "User 4",
    },
    {
      id: 5,
      profilePicture: "assets/person/5.jpeg",
      username: "User 5",
    },
    {
      id: 6,
      profilePicture: "assets/person/6.jpeg",
      username: "User 6",
    },
    {
      id: 7,
      profilePicture: "assets/person/7.jpeg",
      username: "User 7",
    },
    {
      id: 8,
      profilePicture: "assets/person/8.jpeg",
      username: "User 8",
    },
    {
      id: 9,
      profilePicture: "assets/person/9.jpeg",
      username: "User 9",
    },
    {
      id: 10,
      profilePicture: "assets/person/10.jpeg",
      username: "User 10",
    },
    {
      id: 11,
      profilePicture: "assets/person/11.jpeg",
      username: "User 11",
    },
    {
      id: 12,
      profilePicture: "assets/person/12.jpeg",
      username: "User 12",
    },
    {
      id: 13,
      profilePicture: "assets/person/13.jpeg",
      username: "User 13",
    },
    {
      id: 14,
      profilePicture: "assets/person/14.jpeg",
      username: "User 14",
    },
    {
      id: 15,
      profilePicture: "assets/person/15.jpeg",
      username: "User 15",
    },
  ];

  
  export const Posts = [
    {
      id: 1,
      desc: "Love for all, Heated for none - Post 1",
      photo: "assets/post/1.png",
      date: "5 minutes ago",
      userId: 1,
      like: Math.floor(Math.random() * 100),
      comment: Math.floor(Math.random() * 50),
    },
    {
      id: 2,
      desc: "Love for all, Heated for none - Post 2",
      photo: "assets/post/2.jpg",
      date: "10 minutes ago",
      userId: 2,
      like: 105,
      comment: 105,
    },
    {
      id: 3,
      desc: "Love for all, Heated for none - Post 3",
      photo: "assets/post/3.jpg",
      date: "15 minutes ago",
      userId: 3,
      like: 105,
      comment: 105,
    },
    {
      id: 4,
      desc: "Love for all, Heated for none - Post 4",
      photo: "assets/post/4.jpg",
      date: "20 minutes ago",
      userId: 4,
      like: 105,
      comment: 105,
    },
    {
      id: 5,
      desc: "Love for all, Heated for none - Post 5",
      photo: "assets/post/5.jpg",
      date: "25 minutes ago",
      userId: 5,
      like: 105,
      comment: 105,
    },
    {
      id: 6,
      desc: "Love for all, Heated for none - Post 6",
      photo: "assets/post/6.jpg",
      date: "30 minutes ago",
      userId: 6,
      like: 105,
      comment: 105,
    },
    {
      id: 7,
      desc: "Love for all, Heated for none - Post 7",
      photo: "assets/post/7.jpg",
      date: "35 minutes ago",
      userId: 7,
      like: 105,
      comment: 105,
    },
    {
      id: 8,
      desc: "Love for all, Heated for none - Post 8",
      photo: "assets/post/8.jpg",
      date: "40 minutes ago",
      userId: 8,
      like: 105,
      comment: 105,
    },
    {
      id: 9,
      desc: "Love for all, Heated for none - Post 9",
      photo: "assets/post/9.jpg",
      date: "45 minutes ago",
      userId: 9,
      like: 105,
      comment: 105,
    },
    {
      id: 10,
      desc: "Love for all, Heated for none - Post 10",
      photo: "assets/post/10.jpg",
      date: "50 minutes ago",
      userId: 10,
      like: 105,
      comment: 105,
    },
    {
      id: 11,
      desc: "Love for all, Heated for none - Post 11",
      photo: "assets/post/11.jpg",
      date: "55 minutes ago",
      userId: 11,
      like: 1050,
      comment: 105,
    },
    {
      id: 12,
      desc: "Love for all, Heated for none - Post 12",
      photo: "assets/post/12.jpg",
      date: "60 minutes ago",
      userId: 12,
      like: 105,
      comment: 105,
    },
    {
      id: 13,
      desc: "Love for all, Heated for none - Post 13",
      photo: "assets/post/13.jpg",
      date: "65 minutes ago",
      userId: 13,
      like: 105,
      comment: 105,
    },
    {
      id: 14,
      desc: "Love for all, Heated for none - Post 14",
      photo: "assets/post/14.jpg",
      date: "70 minutes ago",
      userId: 14,
      like: 105,
      comment: 105,
    },
    {
      id: 15,
      desc: "Love for all, Heated for none - Post 15",
      photo: "assets/post/15.jpg",
      date: "75 minutes ago",
      userId: 15,
      like: 105,
      comment: 105,
    },
    {
      id: 16,
      desc: "Love for all, Heated for none - Post 16",
      photo: "assets/post/16.jpg",
      date: "80 minutes ago",
      userId: 1,
      like: 105,
      comment: 105,
    },
    {
      id: 17,
      desc: "Love for all, Heated for none - Post 17",
      photo: "assets/post/17.jpg",
      date: "85 minutes ago",
      userId: 2,
      like: 105,
      comment: 105,
    },
    {
      id: 18,
      desc: "Love for all, Heated for none - Post 18",
      photo: "assets/post/18.jpg",
      date: "90 minutes ago",
      userId: 3,
      like: 105,
      comment: 105,
    },
    {
      id: 19,
      desc: "Love for all, Heated for none - Post 19",
      photo: "assets/post/19.jpg",
      date: "95 minutes ago",
      userId: 4,
      like: 105,
      comment: 105,
    },
    {
      id: 20,
      desc: "Love for all, Heated for none - Post 20",
      photo: "assets/post/20.jpg",
      date: "100 minutes ago",
      userId: 5,
      like: 105,
      comment: 105,
    }
  
    ]